### ISSUE TITLE
Can we have options for both profile_perl and the kernel spec? 

### ISSUE THREAD

**Issue by zhouzhen1** [EntropyOrg/p5-Devel-IPerl#44]
I am using ipython 2.20, and with recent release like 0.005, iperl does not work. It seems that earlier ipython does not support "ipython console --kernel xxx".

**Comment by zmughal** [comment]
Hmm, I think I can backport support for both. That'll give me a chance to clean up the code a bit.

In the meantime, you can do this:

1. Make sure that this [file](https://github.com/EntropyOrg/p5-Devel-IPerl/blob/33fa34bac1afdba5b212fbc48b3544e7bca6c115/share/profile/ipython_config.py) is in `~/.ipython/profile_perl/ipython_config.py` and that it contains the same contents for the `c.KernelManager.kernel_cmd` variable.
2. Start IPerl by calling IPython with either: `ipython console --profile perl` or `ipython notebook --profile perl`

Thanks for bringing this up!

**Comment by zmughal** [comment]
I just realised that this might not work since I upgraded the version of the messaging spec to version 5. Could you give it a try and see if there is a problem? I'll try and install an older version of IPython if I can.

I would recommend upgrading the IPython version since there are many bugfixes since that the 2.x release.

**Comment by zhouzhen1** [comment]
Let me close this. I had access to only IPython 2 when I created the issue. Things have changed. And I think we should focus on recent Jupyter versions.
