### ISSUE TITLE
Add B::Keywords to dependencies

### ISSUE THREAD

**Issue by demianriccardi** [EntropyOrg/p5-Devel-IPerl#53]
Just installed Devel::IPerl on a 5.20 threaded perl on OS X 10.11.1.  The install went through after getting Cairo to install; needed to reinstall cairo via homebrew. 

Running a jupyter notebook went into a kernel death spiral until I installed B::Keywords.

It's working now!  Woo!

**Comment by zmughal** [comment]
Some quick notes:

- Cairo:
  Ah, I see why it requires Cairo: `Chart::Clicker`. I shall look into reducing the deps when I get tuits (very soon... my defense is coming up :-D). Or a PR would be appreciated.

- B::Keywords:
  And `B::Keywords` is because of Reply's [Autocomplete::Keywords plugin](https://metacpan.org/source/DOY/Reply-0.37/lib/Reply/Plugin/Autocomplete/Keywords.pm) which is loaded [here](https://github.com/EntropyOrg/p5-Devel-IPerl/blob/master/lib/Devel/IPerl/Kernel/Backend/Reply.pm#L18).
